### This was done to see if changing the dataset can improve the accuracy of the prediction. So, we got a dataset that had considerably cleaner data that the previous one and applied the same steps as before. The accuracy improved for both logistic and dense layer models. In logistic regression we got the accuracy of 82% where as in Dense network we got accuracy from 86% to 90% on different samples. That's a very good improvement from what we got in the previos version.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
from gensim.models import Word2Vec
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [108]:
data = pd.read_csv(r'C:\Users\Dell\Documents\projects\hate speech detection\hate-speech-and-offensive-language-master\data2\HateSpeechDetection.csv')

In [109]:
data

Platform                                            Comment  Hateful
0      Reddit  Damn I thought they had strict gun laws in Ger...        0
1      Reddit  I dont care about what it stands for or anythi...        0
2      Reddit                  It's not a group it's an idea lol        0
3      Reddit                          So it's not just America!        0
4      Reddit  The dog is a spectacular dancer considering he...        0
...       ...                                                ...      ...
2995    4Chan  This is what Kike shilling looks like. Ryan ha...        1
2996    4Chan                            Not bait, they're right        0
2997    4Chan                             I like this one a lot.        0
2998    4Chan           Kikes making money off heroin what’s new        1
2999    4Chan  Desecrate men by making them gay/trannies, and...        1

[3000 rows x 3 columns]

In [110]:
data['Hateful'].value_counts()

0    2400
1     600
Name: Hateful, dtype: int64

In [111]:
X_train, X_test, y_train, y_test = train_test_split(data['Comment'], data['Hateful'], test_size=0.2, random_state=42)


In [112]:
stop_words = set(stopwords.words('english'))
def preprocess(text):
    text = text.lower()
    text = ''.join([word for word in text if word not in string.punctuation])
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(tokens)

X_train = X_train.apply(preprocess)
X_test = X_test.apply(preprocess)

In [113]:
sentences = [sentence.split() for sentence in X_train]
w2v_model = Word2Vec(sentences, vector_size=100, window=5, min_count=5, workers=4)

In [114]:
def vectorize(sentence):
    words = sentence.split()
    words_vecs = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    if len(words_vecs) == 0:
        return np.zeros(100)
    words_vecs = np.array(words_vecs)
    return words_vecs.mean(axis=0)

X_train = np.array([vectorize(sentence) for sentence in X_train])
X_test = np.array([vectorize(sentence) for sentence in X_test])

In [247]:
weights={0:1,1:3.80005}

In [248]:
y_train

642     0
700     0
226     0
1697    0
1010    0
       ..
1638    1
1095    0
1130    0
1294    0
860     1
Name: Hateful, Length: 2400, dtype: int64

In [249]:
clf = LogisticRegression(class_weight=weights)
clf.fit(X_train, y_train)

LogisticRegression(class_weight={0: 1, 1: 3.80005})

In [250]:
y_pred = clf.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Precision:', precision_score(y_test, y_pred,average='weighted' ))
print('Recall:', recall_score(y_test, y_pred,average='weighted' ))
print('F1 score:', f1_score(y_test, y_pred,average='weighted' ))

Accuracy: 0.8216666666666667
Precision: 0.8010954571841993
Recall: 0.8216666666666667
F1 score: 0.8081100976331306


#### Logistic regression evaluation.

In [263]:
clf.predict([vectorize(preprocess(""" """))])

array([0], dtype=int64)

In [246]:
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,

In [155]:
np.array(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,

In [147]:
pd.DataFrame(y_test).value_counts()

Hateful
0          494
1          106
dtype: int64

# Using a deep layer

In [264]:
from keras.models import Sequential
from keras.layers import Dense
import keras
from sklearn.preprocessing import OneHotEncoder

In [265]:
X_test, val_x,  y_test, val_y = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [266]:
enc = OneHotEncoder(handle_unknown = 'ignore')
y_train=pd.DataFrame(y_train)
enc.fit(y_train)

OneHotEncoder(handle_unknown='ignore')

In [267]:
y_train=enc.transform(y_train).toarray()
y_test=pd.DataFrame(y_test)
enc.fit(y_test)
y_test=enc.transform(y_test).toarray()
val_y=pd.DataFrame(val_y)
enc.fit(val_y)
val_y=enc.transform(val_y).toarray()

In [268]:
y_train.shape

(2400, 2)

In [284]:
model = Sequential()

n_cols = 100

model.add(Dense(200, activation='relu', input_shape=(n_cols,)))
model.add(Dense(100, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(2,activation='softmax'))
model.compile(optimizer=keras.optimizers.Adam(0.001),
    loss="categorical_crossentropy",
    metrics=[keras.metrics.CategoricalAccuracy()]
)
model.fit(X_train, y_train, validation_data=(val_x, val_y),epochs=100)

Epoch 1/100
75/75 [==============================] - 1s 4ms/step - loss: 0.5394 - categorical_accuracy: 0.7867 - val_loss: 0.4569 - val_categorical_accuracy: 0.8300
Epoch 2/100
75/75 [==============================] - 0s 2ms/step - loss: 0.5054 - categorical_accuracy: 0.7942 - val_loss: 0.4533 - val_categorical_accuracy: 0.8300
Epoch 3/100
75/75 [==============================] - 0s 2ms/step - loss: 0.4968 - categorical_accuracy: 0.7942 - val_loss: 0.4412 - val_categorical_accuracy: 0.8300
Epoch 4/100
75/75 [==============================] - 0s 2ms/step - loss: 0.4862 - categorical_accuracy: 0.7942 - val_loss: 0.4304 - val_categorical_accuracy: 0.8300
Epoch 5/100
75/75 [==============================] - 0s 2ms/step - loss: 0.4724 - categorical_accuracy: 0.7942 - val_loss: 0.4158 - val_categorical_accuracy: 0.8300
Epoch 6/100
75/75 [==============================] - 0s 2ms/step - loss: 0.4457 - categorical_accuracy: 0.8025 - val_loss: 0.4288 - val_categorical_accuracy: 0.8567
Epoch 7/10

75/75 [==============================] - 0s 3ms/step - loss: 0.1582 - categorical_accuracy: 0.9429 - val_loss: 0.4153 - val_categorical_accuracy: 0.8667
Epoch 100/100
75/75 [==============================] - 0s 2ms/step - loss: 0.1558 - categorical_accuracy: 0.9429 - val_loss: 0.3768 - val_categorical_accuracy: 0.8933


#### Deep network evaluation

In [285]:
model.evaluate(X_test,y_test)

10/10 [==============================] - 0s 1ms/step - loss: 0.3852 - categorical_accuracy: 0.8633


[0.3851660490036011, 0.8633333444595337]

In [103]:
a=vectorize(preprocess("""i hate blacks"""))
a=np.array([a])
a.shape

(1, 100)

In [102]:
model.predict(a)

1/1 [==============================] - 0s 33ms/step


array([[0.06137383, 0.93862617]], dtype=float32)

In [92]:
v=[a]
v=np.array(v)
v.shape

(1, 100)

# checking if the data imbalance is the cause of less accuracy

In [130]:
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks
from imblearn.under_sampling import NearMiss

In [124]:
resample=SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
X, y = resample.fit_resample(X_train, y_train)

In [125]:
y

0        0
1        2
2        1
3        1
4        1
        ..
46039    2
46040    2
46041    2
46042    2
46043    2
Name: class, Length: 46044, dtype: int64

In [141]:
undersample = NearMiss(version=1, n_neighbors=3)
X, y = undersample.fit_resample(X_train, y_train)